'use strict';
try{
    x=10
    // mifuncion();
} catch(error) {
    console.log(error)
} finally {
    console.log ( "Termina la revision de errores");
}


console.log("continuamos... ")